### ISSUE TITLE
for loop issue

### ISSUE THREAD

**Issue by Johny1010** [piotr-zawadzki-kodilla/8-9-petle-i-choinka#1]
Masz w tym momencie tak:
for (var i = wys; i > n; i--) {
	star += " ";
}
for (var i = 1; i <= n * 2 - 1; i++) {
	star += "*";
}

2 razy deklarujesz i (w drugim for masz ponowna deklaracje var i = 1;). Wystarczy tutaj przypisanie nowej wartosci do i (bez var)

**Comment by piotr-zawadzki-kodilla** [comment]
Racja, nie zauważyłem. Poprawione :)
